name: 'Bump Version'
description: 'Bump version of the project'

inputs:
  type:
    required: true
    description: 'The type of version to bump'
    type: choice
    default: 'patch'
    options:
      - 'patch'
      - 'minor'
      - 'major'



runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      uses: ./.github/actions/install

    - name: Old version
      # Set old version as an output of this step
      run: echo "old_version=$(poetry version -s)" >> $GITHUB_ENV
      shell: bash

    - name: Bump Version
      run: make bumpversion ${{ inputs.type }}
      shell: bash

    - name: New version
      # Set new version as an output of this step
      run: echo "new_version=$(poetry version -s)" >> $GITHUB_ENV
      shell: bash
