name: Lint & Test Python Package

on:
  pull_request:
    branches:
      - main
      - docs/*

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Lint code
        uses: pre-commit/action@v3.0.1

  test:
    needs: lint
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - name: Test on Python ${{ matrix.python-version }} on ${{matrix.os}}
        uses: ./.github/actions/test
        with:
          python-version: ${{ matrix.python-version }}

  codecov:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: upload coverage reports to Codecov
        uses: ./.github/actions/codecov
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  # deploy-docs:
  #   needs: test
  #   # if: github.ref == 'refs/heads/docs/*'
  #   runs-on: ubuntu-latest
  #   env:
  #     VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  #     VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: change directory
  #       run: cd docs
  #     - name: Install Vercel CLI
  #       run: npm install --global vercel

  #     - name: Pull Vercel Environment Information
  #       run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

  #     - name: Build Project Artifacts
  #       run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

  #     - name: Deploy Project Artifacts
  #       run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
