name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      uses: ./.github/actions/install
    - name: bump version
      uses: ./.github/actions/bump-version

    - name: Build and Deploy
      uses: ./.github/actions/build-deploy
      with:
        pypi-token: ${{ secrets.PYPI_API_TOKEN }}
