name: Upload Python Package

on:
  release:
    types: [published]
  push:
    branches:
      - ouhammou/test-bumpversion

permissions:
  contents: write
  pull-requests: write

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      uses: ./.github/actions/install
    - name: bump version
      uses: ./.github/actions/bump-version
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.ACTIONS_TOKEN }}

    # - name: Build and Deploy
    #   uses: ./.github/actions/build-deploy
    #   with:
    #     pypi-token: ${{ secrets.PYPI_API_TOKEN }}
