name: Upload Python Package

on:
  release:
    types: [published]
  push:
    branches:
      - ouhammou/test-bumpversion

permissions:
  contents: write
  actions: write

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      uses: ./.github/actions/install
    - name: bump version
      uses: ./.github/actions/bump-version
    - name: Commit files
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -a -m "Add changes"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}

    # - name: Build and Deploy
    #   uses: ./.github/actions/build-deploy
    #   with:
    #     pypi-token: ${{ secrets.PYPI_API_TOKEN }}
